name: evex
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.12.1
  cloud_firestore: ^5.6.5
  firebase_auth: ^5.5.1
  geolocator: ^13.0.4
  url_launcher: ^6.3.1
  http: ^0.13.3
  intl: ^0.20.2
  flutter_local_notifications: ^18.0.1
  timezone: ^0.9.4
  permission_handler: ^12.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/icone_evex.png"

flutter:
  uses-material-design: true
  assets: 
    - assets/images/branco.png
    - assets/images/escolha.png
    - assets/images/topo.png
    - assets/images/icone_evex.png
